### PR TITLE
Backport windows to 2020.2

### PR DESCRIPTION
**Pull request by isuruf**
This reverts commit 54e23d25d2ec77f2492038eb31db067077089038, reversing
changes made to 50ed5353d18b5e90ad188061eaf90d9bcd7a393a.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
We should explain why in the PR text here so we don't forget later.

**Comment by isuruf** [comment]
Because we are still using this version in blas-feedstock and channel priority removes the 2020.2 from defaults because we have only 2020.4

**Comment by beckermr** [comment]
Awesome thank you! LGTM when you are happy!

**Comment by napetrov** [comment]
@isuruf  can we keep MKL on 2020.2 but still update daal to 2020.3?

**Comment by isuruf** [comment]
Oops. I meant to merge this to a branch instead of master. I fixed it. `master` is on `2020.3` and there's a `2020.2` branch

**Pull request merged**
