### PR TITLE
Update mkl and dal to 2021.3

### PR DESCRIPTION
**Pull request by PetrovKP**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by PetrovKP** [comment]
@conda-forge-admin, please rerender

**Review by napetrov — APPROVED** [review]

**Comment by PetrovKP** [comment]
@isuruf please, review this PR

**Comment by isuruf** [comment]
Thanks

**Comment by isuruf** [comment]
Btw, we'll be happy to have you as a maintainer and give you commit rights.

**Comment by PetrovKP** [comment]
@isuruf Could you please restart CI? something happened when loading a Windows packages: https://github.com/conda-forge/intel_repack-feedstock/runs/2976426573

**Comment by isuruf** [comment]
Done

**Pull request merged**
