### PR TITLE
Repackage mkl/daal software directly from Intel

### PR DESCRIPTION
**Pull request by nowster**
- Remove anything that's not built for conda-forge.
- Add packaging of mkl-static.
- Add checksums.
- Enable win-64 builds.

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by nowster** [comment]
> The jinja2 that kept the non-conda-forge bits in the recipe was purposeful. Can we add that back?

I removed it because this is a conda-forge feedstock and its presence seemed to be a legacy of a historic recipe obtained from outwith conda-forge. Does it serve any purpose within conda-forge?

**Comment by beckermr** [comment]
No, but anaconda inc forks our recipes to use for their builds. They provide conda-forge a huge amount of support. Leaving in things they need but commented out is a small gesture we can make in return.

**Comment by nowster** [comment]
This is a from-scratch refactoring of the recipe. As conda-forge doesn't package `intel-openmp` a method and instructions for packaging it weren't coded. Reinstating the removed jinja2 parts of `meta.yaml` won't result in anything usable.

**Comment by beckermr** [comment]
Understood and thanks. 

bump to @isuruf for his thoughts here

**Comment by beckermr** [comment]
Bump @conda-forge/core. I don't think I can properly evaluate this pr on my own. Thoughts?

**Comment by msarahan** [comment]
What's the advantage of doing the repackaging from more raw sources? Intel produces the packages on the Anaconda.org Intel channel. Any repack you do from another source circumvents the QA that they do on their conda packages. If you are missing something from their conda packages, it's probably better to ask them to directly provide conda packages with what you need, and perhaps use your custom packages until they are able to.

Pinging key intel/anaconda people: @oleksandr-pavlyk @tomashek @jjhelmus @csoja

**Comment by SylvainCorlay** [comment]
> What's the advantage of doing the repackaging from more raw sources?

The benefit that I see is that it is more in line with general approach of conda-forge to build things instead of getting pre-built binaries.

**Comment by SylvainCorlay** [comment]
If we want to favor the official intel build, we could add a track_feature and a mutex package to de-priorize this.

If we decide to make the  from-scratch build the main one, we can change the default?

**Comment by nowster** [comment]
Is it likely that Intel will open up the packaging process to allow conda-forge and others to build conda packages directly from resources on Intel's own site? (For traceability and ensuring correct provenance.)

**Comment by napetrov** [comment]
@nowster  This is relevantly complicated question. On one hand we are moving to opensource development for some of components while there for sure long path to go and i don't think that in feasible future this will cover majority of components. But as an example we recently add daal4py conda-forge build from sources and will keep working in this direction. 

As for opening packaging process - it might be easier but so far there is no plans to expose this besides probably package that are already open sourced.

Another important caveat is QA - for binaries provided by Intel we ensure full validation while for packages build in conda-forge from sources we are obviously not doing same level of validation. And more importantly from performance perspective we might have different results due to use of different compilers in some cases. 

Although i really like an idea behind this change - i see one large problem - it's maintenance. Assuming this change was merged 4 months ago it would take no rewriting large portion of it to adopt to new structure/naming that is avaialbe as part of oneAPI releases that we will have going forward. While in case of reusing conda packages from Intel channel this would be mostly solved there already.

**Comment by napetrov** [comment]
There were multiple iterations of structure changes happened to intel distributions and this request can't be integrated

**Pull request closed without merging**
