### PR TITLE
Set default stdlib requirement to mkl

### PR DESCRIPTION
**Pull request by ZzEeKkAa**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

As mentioned by @h-vetinari  at https://github.com/conda-forge/intel_repack-feedstock/pull/82/files/462540bf2bc86a600f7be112379d6def0ce68859#r1835172927 there was an error with setting correct glibc dependency

### CODE REVIEW

**Comment by ZzEeKkAa** [comment]
Thank you @h-vetinari for finding the issue. Could you please review this PR?

**Comment by oleksandr-pavlyk** [comment]
Just making sure that change to replace `- {{ c_stdlib }}_{{ target_platform }} >={{ c_stdlib_sycl_version }} # [linux]` with `- {{ c_stdlib }}_{{ target_platform }} {{ c_stdlib_sycl_version }} # [linux]`  was purely stylistic. 

The real issue was that `{{ c_stdlib_sycl_version }}` was used in non-SYCL components, i.e., `mkl`.

**Comment by ZzEeKkAa** [comment]
> Just making sure that change to replace `- {{ c_stdlib }}_{{ target_platform }} >={{ c_stdlib_sycl_version }} # [linux]` with `- {{ c_stdlib }}_{{ target_platform }} {{ c_stdlib_sycl_version }} # [linux]` was purely stylistic.
> 
> The real issue was that `{{ c_stdlib_sycl_version }}` was used in non-SYCL components, i.e., `mkl`.

Yes, exactly. I've checked that removing `>=` does not affect result glibc pinning

**Review by oleksandr-pavlyk — APPROVED** [review]
LGTM. Thank you for fixing it @ZzEeKkAa

**Review by h-vetinari — APPROVED** [review]
Thanks for the quick response!

**Pull request merged**
