### PR TITLE
2021.5 update

### PR DESCRIPTION
**Pull request by itearsl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by itearsl** [comment]
@conda-forge-admin, please rerender

**Comment by itearsl** [comment]
@conda-forge-admin, please restart ci

**Comment by Pahandrovich** [comment]
@conda-forge-admin, please restart ci

**Comment by h-vetinari** [comment]
Great to see a new version!

Regarding #26, there was a [comment](https://github.com/conda-forge/intel_repack-feedstock/pull/29#issuecomment-941798654) in #29 (my emphasis):
> @sknepper: Intel oneMKL 2021.4 does not support LAPACK 3.9.1. Based on the changes in LAPACK 3.9.1 (more than just simple bug fixes), and the release of LAPACK 3.10, we decided to align to LAPACK 3.10 directly. _**The soonest that would be supported would be in Intel oneMKL 2022.0**_. FYI, we discovered an issue with the *lartg changes in LAPACK 3.10 (see [here](https://github.com/Reference-LAPACK/lapack/issues/629)), which we would work around in Intel oneMKL.

Since the mkl version here is set to 2022.0 already, I wanted to ask if this is already considered LAPACK 3.10-compatible?

**Review by napetrov — APPROVED** [review]
Looks good

**Comment by h-vetinari** [comment]
Could someone comment on the lapack compatibility level please? 🙃

**Comment by sknepper** [comment]
Intel oneMKL 2022.0 does not support LAPACK 3.9.1/3.10. The soonest that would be supported would be in Intel oneMKL 2022.1. The oneMKL release notes will include this change once it is made.

**Pull request merged**
